### ISSUE TITLE
ValueError: `dataset` input should have multiple elements.

### ISSUE THREAD

**Issue by porkfan** [shohei-kojima/MEGAnE#13]
I hope this message finds you well. I encountered a bug while using MEGAnE and I was hoping to get some assistance with it.
I have been using your software for my plant data, and I have encountered an issue with the output files. Specifically, the files MEI_final_failed_genotyped.vcf and MEI_final_failed_genotyped.bed contain the expected data, but the files absent_MEs.bed and absent_MEs_transduction.bed are empty.
This is the content of log/call_gangan_genotype.err :
2023-09-10 13:09:09,025:INFO:Initial check started.
2023-09-10 13:09:10,775:INFO:estimated read lenth = 150
2023-09-10 13:09:10,805:INFO:All 3332 main chromosome(s) were found in /public/home/yfchen/MEVs/02.FinalBam/gangan.bam.
2023-09-10 13:09:10,805:INFO:"-no_sex_chr" option was specified. All chromosomes will be treated as autosomes.
2023-09-10 13:09:10,815:INFO:Preprocessing started.
2023-09-10 13:09:11,360:INFO:N=9015 repeats found in /public/home/yfchen/MEVs/modified_Dfam_3708.rep. N=9015 will be analyzed. N=0 will be excluded due to non-ME repeats.
2023-09-10 14:24:55,411:INFO:Discordant read search started.
2023-09-10 14:26:17,972:INFO:Screening results:nonXY_reads=87183903,X_reads=0,Y_reads=0,chimeric_reads=3560259,hybrid_reads=1810458,pA_reads=18277,absent_reads=87791
2023-09-10 14:26:18,033:INFO:estimated autosome depth = 13
2023-09-10 14:26:18,034:INFO:"-no_sex_chr" option was specified. All chromosomes will be treated as autosomes.
2023-09-10 14:26:18,209:INFO:Clipped read processing started.
2023-09-10 14:50:26,130:INFO:Unmapped read processing started.
2023-09-10 14:50:26,136:INFO:Hybrid read processing started.
2023-09-10 14:50:48,738:INFO:Integration junction search (outside of TEs) started.
2023-09-10 14:51:02,919:INFO:Integration junction search (nested in TEs) started.
2023-09-10 14:53:15,735:INFO:Filtering started.
2023-09-10 14:53:18,305:WARNING:Not enough data found. Cannot automatically determine thresholds for MEI filtering. Please check if your data contains discordant reads enough for auto-filtering. Proceed anyway.
2023-09-10 14:54:38,526:INFO:[5064] ME insertion candidates found.
2023-09-10 14:54:38,534:INFO:ME insertion search finished!
2023-09-10 14:54:38,537:INFO:Absent ME search started.
2023-09-10 14:54:39,663:INFO:0 absent ME candidates found.
2023-09-10 14:54:39,663:INFO:Absent ME search finished!
2023-09-10 14:54:39,668:INFO:pME search finished!
2023-09-10 14:54:39,681:INFO:Limit BAM/CRAM started.
2023-09-10 14:59:12,907:INFO:Evidence search started, insertion: 01_gangan_result/MEI_final_failed.bed
/usr/local/bin/MEGAnE/scripts/allele_count_ins.py:828: RuntimeWarning: divide by zero encountered in double_scalars
  r_squared_few= 1 - (rss / tss)
2023-09-10 14:59:35,755:INFO:Evidence merge started, insertion: 01_gangan_result/MEI_final_failed.bed
2023-09-10 14:59:43,934:INFO:4745 high-confidence pMEI found.
2023-09-10 14:59:43,951:INFO:Did output VCF, insertion: 01_gangan_result/MEI_final_failed.bed
2023-09-10 14:59:43,967:INFO:Evidence search started, absent MEs.
/opt/conda/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/opt/conda/lib/python3.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
2023-09-10 14:59:44,766:ERROR:
Traceback (most recent call last):
  File "/usr/local/bin/MEGAnE/scripts/allele_count_abs.py", line 525, in evaluate_bp_depth
    abs_kernel=stats.gaussian_kde(min_ratios)
  File "/opt/conda/lib/python3.7/site-packages/scipy/stats/kde.py", line 195, in __init__
    raise ValueError("`dataset` input should have multiple elements.")
ValueError: `dataset` input should have multiple elements.

Could you please provide some guidance or suggestions on how to resolve this bug? I would greatly appreciate any help you can provide.

Thank you for your time and attention. 

Best regards,
Chenyf

**Comment by zpliu1126** [comment]
Hi porkfan~
 Have your issues been resolved? I've encountered the same problem.

Best wishes zpliu

**Comment by Yuanqingq** [comment]
Hello~ 
I have the sample problem too. Have you solved it ?

Best,
Yuanqingq

**Comment by swainasish** [comment]
I also have the the same problem.
Can anyone guide how to solve this error?
Best,
Asish

**Comment by Xuelei-Dai** [comment]
We all encountered the same problem, but the author did not maintain the software after publishing the article and simply disappeared???
