### ISSUE TITLE
Step:1 failed with singularity

### ISSUE THREAD

**Issue by jayramr** [shohei-kojima/MEGAnE#16]
I'm getting below error while performing the step 1. Please advise 

```
$singularity exec MEGAnE.sif call_genotype_37 -i sam_files/X2-10_S8_aligned.bam -fa XENLA_genome/XENLA_9.2_genome.fa -mk megane_kmer_set_test/reference_human_genome.mk -outdir MEGAnE_result_test -sample_name test_sample_X2-10_S8 -p 24

2023-11-08 13:40:21,144:INFO:Initial check started.
2023-11-08 13:40:21,634:INFO:Generating BAM index...
[E::hts_idx_push] Chromosome blocks not continuous
2023-11-08 13:40:21,655:ERROR:
Traceback (most recent call last):
  File "/usr/local/bin/MEGAnE/scripts/initial_check.py", line 129, in check
    pysam.index(args.b, '-@ %d' % args.p)
  File "/opt/conda/lib/python3.7/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: failed to create index for "sam_files/X2-10_S8_aligned.bam"\n'
```

**Comment by jayramr** [comment]
@shohei-kojima  Kindly advise on this error.

**Comment by jayramr** [comment]
Hi, 

any response on this.

**Comment by swainasish** [comment]
I have also same error, I sorted the bam file but having another error again.

**Comment by jayramr** [comment]
@swainasish may i know how you sorted the bam file?

**Comment by swainasish** [comment]
@jayramr I sort the bam file using samtools, same can be done using sam file also
```
samtools sort myfile.bam -o myfile_sorted.bam

```
