### ISSUE TITLE
ValueError: `dataset` input should have multiple elements.

### ISSUE THREAD

**Issue by swainasish** [shohei-kojima/MEGAnE#21]
I used dragmap to generate the bam file and samtool to sort it, the command I used
```
singularity exec ${megane_sif} call_genotype_38 \
-i $bam_dir \
-fa $ref_genome \
-mk $mk_file \
-outdir $out_dir \
-sample_name test_sample \
-p 10 -skip_unmapped
```

![image](https://github.com/shohei-kojima/MEGAnE/assets/75718309/c93a257e-b9b9-49f6-93ef-a38aa6299cca)

**Comment by Xuelei-Dai** [comment]
This author is really unreliable

**Comment by lindenb** [comment]
same problem here.
```

/opt/conda/lib/python3.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
2025-01-21 13:05:30,691:ERROR:
Traceback (most recent call last):
  File "/usr/local/bin/MEGAnE/scripts/allele_count_abs.py", line 525, in evaluate_bp_depth
    abs_kernel=stats.gaussian_kde(min_ratios)
  File "/opt/conda/lib/python3.7/site-packages/scipy/stats/kde.py", line 195, in __init__
    raise ValueError("`dataset` input should have multiple elements.")
ValueError: `dataset` input should have multiple elements.

```

command was:

```
cut -f 1 "hs37d5_all_chr.fasta.fai" | awk '($1   ~ /^(chr)?[0-9XY]+$/)' > chr.list

call_genotype_37 \
        -i ${bam} \
        -fa hs37d5_all_chr.fasta \
        -mk REF.mk \
        -mainchr ./chr.list \
        -outdir OUT \
        -sample_name "${SAMPLE}" \
        -p 1
```
