### ISSUE TITLE
Error after "Limit BAM/CRAM started"

### ISSUE THREAD

**Issue by xuxif** [shohei-kojima/MEGAnE#8]
Traceback (most recent call last):
  File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth
    if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]:
KeyError: '12'

**Comment by xuxif** [comment]
I use MEGAnE to analysis HG002 from GIAB. And the bam file is download from GIAB.

**Comment by netwchao** [comment]
I encountered a similar problem as you @xuxif 
2023-05-19 07:23:18,330:ERROR:
Traceback (most recent call last):
  File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth
    if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]:
KeyError: '1'

When you have the convenience, I hope you can provide an answer to this error. Thanks @shohei-kojima

**Comment by xuxif** [comment]
作者没有回复我，我用了另外的工具代替

**Comment by xuxif** [comment]
> I encountered a similar problem as you @xuxif 2023-05-19 07:23:18,330:ERROR: Traceback (most recent call last): File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]: KeyError: '1'
> 
> When you have the convenience, I hope you can provide an answer to this error. Thanks @shohei-kojima

作者没有回复我，很久了，我用了其他工具

**Comment by Wchao110** [comment]
> > I encountered a similar problem as you @xuxif 2023-05-19 07:23:18,330:ERROR: Traceback (most recent call last): File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]: KeyError: '1'
> > When you have the convenience, I hope you can provide an answer to this error. Thanks @shohei-kojima
> 
> 作者没有回复我，很久了，我用了其他工具

兄弟，你好。可以分享下你现在用的工具嘛？感谢

**Comment by xuxif** [comment]
> > > I encountered a similar problem as you @xuxif 2023-05-19 07:23:18,330:ERROR: Traceback (most recent call last): File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]: KeyError: '1'
> > > When you have the convenience, I hope you can provide an answer to this error. Thanks @shohei-kojima
> > 
> > 
> > 作者没有回复我，很久了，我用了其他工具
> 
> 兄弟，你好。可以分享下你现在用的工具嘛？感谢

https://github.com/xuxif/DeepMEI
我自己做的工具，我用这个工具是为了对比，结果报错

**Comment by Wchao110** [comment]
> > > > I encountered a similar problem as you @xuxif 2023-05-19 07:23:18,330:ERROR: Traceback (most recent call last): File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]: KeyError: '1'
> > > > When you have the convenience, I hope you can provide an answer to this error. Thanks @shohei-kojima
> > > 
> > > 
> > > 作者没有回复我，很久了，我用了其他工具
> > 
> > 
> > 兄弟，你好。可以分享下你现在用的工具嘛？感谢
> 
> https://github.com/xuxif/DeepMEI 我自己做的工具，我用这个工具是为了对比，结果报错

优秀，祝你早日在高水平杂志发表这项成果。

**Comment by xuxif** [comment]
> > > > > I encountered a similar problem as you @xuxif 2023-05-19 07:23:18,330:ERROR: Traceback (most recent call last): File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]: KeyError: '1'
> > > > > When you have the convenience, I hope you can provide an answer to this error. Thanks @shohei-kojima
> > > > 
> > > > 
> > > > 作者没有回复我，很久了，我用了其他工具
> > > 
> > > 
> > > 兄弟，你好。可以分享下你现在用的工具嘛？感谢
> > 
> > 
> > https://github.com/xuxif/DeepMEI 我自己做的工具，我用这个工具是为了对比，结果报错
> 
> 优秀，祝你早日在高水平杂志发表这项成果。

不太容易，国外这些叼毛 很压国内的文章，被超过5个杂志拒绝了

**Comment by Wchao110** [comment]
> > > > > > I encountered a similar problem as you @xuxif 2023-05-19 07:23:18,330:ERROR: Traceback (most recent call last): File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]: KeyError: '1'
> > > > > > When you have the convenience, I hope you can provide an answer to this error. Thanks @shohei-kojima
> > > > > 
> > > > > 
> > > > > 作者没有回复我，很久了，我用了其他工具
> > > > 
> > > > 
> > > > 兄弟，你好。可以分享下你现在用的工具嘛？感谢
> > > 
> > > 
> > > https://github.com/xuxif/DeepMEI 我自己做的工具，我用这个工具是为了对比，结果报错
> > 
> > 
> > 优秀，祝你早日在高水平杂志发表这项成果。
> 
> 不太容易，国外这些叼毛 很压国内的文章，被超过5个杂志拒绝了

这种情况的话，预印版应该早点放出来，加油

**Comment by shohei-kojima** [comment]
Sorry everyone for my late response and a bug in MEGAnE.
Could you let me know which GIAB BAM file you used?
Or what mapper (e.g. BWA or DRAGEN) did you use to map fastq?
I would appreciate it if you could let me know some information about your input file.

PS, it is very nice to see you are developing a MEV detection tool using deep learning. I was thinking about doing it, but it was too awkward ;)

**Comment by xuxif** [comment]
> Sorry everyone for my late response and a bug in MEGAnE. Could you let me know which GIAB BAM file you used? Or what mapper (e.g. BWA or DRAGEN) did you use to map fastq? I would appreciate it if you could let me know some information about your input file.
> 
> PS, it is very nice to see you are developing a MEV detection tool using deep learning. I was thinking about doing it, but it was too awkward ;)

I utilized the BWA mapper and the HG002 (60x) BAM file for my analysis. Additionally, I have thoroughly reviewed your manual script on BioRxiv. Could you please let me know the journal you have chosen for publication?
On a related note, I also submitted my manual script to BioRxiv but encountered rejections from three different journals.

**Comment by shohei-kojima** [comment]
Thank you for the information. BWA and the depth of the WGS seem no problem.
Could you also let me know which reference genome (e.g. GRCh38DH, hs37d5) you used, and the style of the chromosome names (e.g. chr1 or 1) in the reference genome? It is possible that, for example, if you use hs37d5-like reference but if the chr name is UCSC style (i.e. chr1), this may cause an issue.

Sorry to hear you got some rejections. I think the use of deep learning is a good progress to this field. Judging from your preprint mostly focus on tool development, I think you have a good chance to publish in Bioinformatics. As you would probably know, ERVcaller is published in Bioinformatics.

We recently published it in Nature Genetics:
https://www.nature.com/articles/s41588-023-01390-2

**Comment by xuxif** [comment]
The reference genome is hs37d5 and do not include 'chr'.

**Comment by Xuelei-Dai** [comment]
> > > > > > > I encountered a similar problem as you @xuxif 2023-05-19 07:23:18,330:ERROR: Traceback (most recent call last): File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]: KeyError: '1'
> > > > > > > When you have the convenience, I hope you can provide an answer to this error. Thanks @shohei-kojima
> > > > > > 
> > > > > > 
> > > > > > 作者没有回复我，很久了，我用了其他工具
> > > > > 
> > > > > 
> > > > > 兄弟，你好。可以分享下你现在用的工具嘛？感谢
> > > > 
> > > > 
> > > > https://github.com/xuxif/DeepMEI 我自己做的工具，我用这个工具是为了对比，结果报错
> > > 
> > > 
> > > 优秀，祝你早日在高水平杂志发表这项成果。
> > 
> > 
> > 不太容易，国外这些叼毛 很压国内的文章，被超过5个杂志拒绝了
> 
> 这种情况的话，预印版应该早点放出来，加油

他这个软件很多bug，根本跑不起来，他的issue中基本没解决别人提出来的问题，你@xuxif  这个软件目前出来了吗？

**Comment by xuxif** [comment]
> > > > > > > > I encountered a similar problem as you @xuxif 2023-05-19 07:23:18,330:ERROR: Traceback (most recent call last): File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]: KeyError: '1'
> > > > > > > > When you have the convenience, I hope you can provide an answer to this error. Thanks @shohei-kojima
> > > > > > > 
> > > > > > > 
> > > > > > > 作者没有回复我，很久了，我用了其他工具
> > > > > > 
> > > > > > 
> > > > > > 兄弟，你好。可以分享下你现在用的工具嘛？感谢
> > > > > 
> > > > > 
> > > > > https://github.com/xuxif/DeepMEI 我自己做的工具，我用这个工具是为了对比，结果报错
> > > > 
> > > > 
> > > > 优秀，祝你早日在高水平杂志发表这项成果。
> > > 
> > > 
> > > 不太容易，国外这些叼毛 很压国内的文章，被超过5个杂志拒绝了
> > 
> > 
> > 这种情况的话，预印版应该早点放出来，加油
> 
> 他这个软件很多bug，根本跑不起来，他的issue中基本没解决别人提出来的问题，你@xuxif 这个软件目前出来了吗？

我认可作者回复 是参考基因组版本问题，但是具体怎么解决我不知道， 但是有一点啊 岛国人 听说有工匠精神，可能他在憋大招

**Comment by Xuelei-Dai** [comment]
> > > > > > > > > I encountered a similar problem as you @xuxif 2023-05-19 07:23:18,330:ERROR: Traceback (most recent call last): File "/usr/local/bin/MEGAnE/scripts/allele_count_ins.py", line 331, in evaluate_tsd_depth if ls[0] in dep and min_pos >= tsd_flank_len and (max_pos + tsd_flank_len) <= fai[ls[0]]: KeyError: '1'
> > > > > > > > > When you have the convenience, I hope you can provide an answer to this error. Thanks @shohei-kojima
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 作者没有回复我，很久了，我用了其他工具
> > > > > > > 
> > > > > > > 
> > > > > > > 兄弟，你好。可以分享下你现在用的工具嘛？感谢
> > > > > > 
> > > > > > 
> > > > > > https://github.com/xuxif/DeepMEI 我自己做的工具，我用这个工具是为了对比，结果报错
> > > > > 
> > > > > 
> > > > > 优秀，祝你早日在高水平杂志发表这项成果。
> > > > 
> > > > 
> > > > 不太容易，国外这些叼毛 很压国内的文章，被超过5个杂志拒绝了
> > > 
> > > 
> > > 这种情况的话，预印版应该早点放出来，加油
> > 
> > 
> > 他这个软件很多bug，根本跑不起来，他的issue中基本没解决别人提出来的问题，你@xuxif 这个软件目前出来了吗？
> 
> 我认可作者回复 是参考基因组版本问题，但是具体怎么解决我不知道， 但是有一点啊 岛国人 听说有工匠精神，可能他在憋大招

小日子这不解决问题的态度，着实让使用该软软件的人难受，你这个软件跑通了没，是否也有ValueError: `dataset` input should have multiple elements.的问题

**Comment by Xuelei-Dai** [comment]
![1](https://github.com/shohei-kojima/MEGAnE/assets/35028002/bef924be-8851-421c-9ba2-86a124402d74)


目前基本就只能跑出这些文件
